# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetaxeptPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currencycode', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255)),
                ('ordernumber', models.CharField(max_length=32)),
                ('flagged', models.NullBooleanField()),
                ('responsecode', models.CharField(blank=True, max_length=3, null=True)),
                ('responsesource', models.CharField(blank=True, max_length=20, null=True)),
                ('responsetext', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetaxeptTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32)),
                ('operation', models.CharField(choices=[(b'AUTH', b'AUTH'), (b'SALE', b'SALE'), (b'CAPTURE', b'CAPTURE'), (b'CREDIT', b'CREDIT'), (b'ANNUL', b'ANNUL')], max_length=7)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('flagged', models.BooleanField()),
                ('responsecode', models.CharField(blank=True, max_length=3, null=True)),
                ('responsesource', models.CharField(blank=True, max_length=20, null=True)),
                ('responsetext', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetaxeptRecurringPayment',
            fields=[
                ('netaxeptpayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djnetaxept.NetaxeptPayment')),
                ('recurring_type', models.CharField(choices=[(b'S', b'S'), (b'R', b'R')], max_length=1)),
                ('minimum_frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            bases=('djnetaxept.netaxeptpayment',),
        ),
        migrations.AddField(
            model_name='netaxepttransaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djnetaxept.NetaxeptPayment'),
        ),
    ]
