# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djnetaxept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netaxeptpayment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 10, 11, 27, 30, 886859, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netaxeptpayment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='netaxepttransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 10, 11, 27, 35, 971944, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netaxepttransaction',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
