# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnetaxept', '0004_auto_20161115_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netaxepttransaction',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
