# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnetaxept', '0005_auto_20161115_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netaxeptpayment',
            name='responsecode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='netaxepttransaction',
            name='responsecode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
